version: '3.8'
services:
  myRabbit:
    ports:
      - '5672:5672'
    image: rabbitmq:3.8.1-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_DEFAULT_VHOST=myvhost
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq

  mongo:
    ports:
      - '27017:27017'
    image: mongo
    volumes:
      - ./data/mongo:/data/db

  postgres_db:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  consumer:
    ports:
      - '81:80'
    build: ./consumer
    environment:
      - MONGO_URI=mongodb://mongo_db:27017/test
      - EXPRESS_PORT=8080
      - RABBIT_URI=amqp://admin:admin@myRabbit:5672/myvhost
    depends_on:
      - myRabbit
      - mongo

  producer:
    restart: on-failure
    ports:
      - '80:80'
    build: ./producer
    environment:
      - PG_URI=postgres://postgres:postgres@postgres_db:5432/postgres
      - EXPRESS_PORT=8080
      - RABBIT_URI=amqp://admin:admin@myRabbit:5672/myvhost
    depends_on:
      - myRabbit
      - mongo
